### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by Yihwan** [Yihwan/robinhood-clone#6]
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login without signing up
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by Yihwan** [comment]
[] Users can sign up, sign in, log out
[] Users can use a demo login without signing up
[] Adequate styling
[] Smooth, bug-free navigation
[] Adequate and appropriate seeds to demonstrate the feature

**Comment by ajansel** [comment]
All good here, nicely done!
