### ISSUE TITLE
PA Review: Dashboard + Portfolio

### ISSUE THREAD

**Issue by Yihwan** [Yihwan/robinhood-clone#8]
- [x] Users can see an index of possible assets.
- [x] Users can track portfolio amount.
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

(actual buying and selling was spec'd to MVP 2 since that is where the tradeform will live)

**Comment by ajansel** [comment]
All done, looks great!
