### ISSUE TITLE
PA Review: Asset Detail 

### ISSUE THREAD

**Issue by Yihwan** [Yihwan/robinhood-clone#9]
- [x] Users can buy or sell an asset.
- [x] Users can conduct basic market research on an asset.
- [x] Includes sidebar to trade asset as well as basic information about the asset.
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by ajansel** [comment]
Great work!
